/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.6.10"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-model
    implementation("org.eclipse.rdf4j:rdf4j-model:3.7.2")

    // https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-rio-turtle
    implementation("org.eclipse.rdf4j:rdf4j-rio-turtle:3.7.2")

    // https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-rio-rdfxml
    implementation("org.eclipse.rdf4j:rdf4j-rio-rdfxml:3.7.2")
}

application {
    // Define the main class for the application.
    mainClass.set("SchemaTransformer.AppKt")
}
