@startuml ConstraintDiagram

class "sh:Shape"
class "owl:Class"
class "sh:NodeShape" 
class "rdfs:Datatype"
class "sh:PropertyShape" {
    sh:minCount :  "xsd:integer"
    sh:maxCount :  "xsd:integer"
}
class "rdf:List" 
class "rdf:Property" 
abstract class "owl:Thing" { 
 rdfs:comment : "xsd:string" 
}

"owl:Thing" <|--  "rdf:Property"

"owl:Thing" <|--  "rdfs:Datatype"
"owl:Thing" <|--  "sh:Shape"
"owl:Thing" <|--  "owl:Class"
"owl:Thing" <|--  "rdf:List"

"sh:Shape" <|--   "sh:NodeShape"
"sh:Shape" <|--   "sh:PropertyShape"

"sh:NodeShape" --> "sh:PropertyShape" : "sh:property"
"sh:NodeShape" --> "owl:Class" : "sh:targetClass"
"sh:PropertyShape" -> "rdf:Property" : "sh:path"
"sh:Shape" -> "rdf:List" : "sh:in"
"sh:PropertyShape" -> "sh:NodeShape" : "sh:node"
"sh:PropertyShape" -> "rdfs:Datatype" : "sh:datatype"


@enduml