@startuml

class "owl:Class" [[http://www.w3.org/2000/01/rdf-schema#Class]] #LightGreen
class "owl:DatatypeProperty" [[http://www.w3.org/2002/07/owl#DatatypeProperty]] #LightGreen
class "owl:ObjectProperty" [[http://www.w3.org/2002/07/owl#ObjectProperty]] #LightGreen
class "owl:TransitiveProperty" [[http://www.w3.org/2002/07/owl#TransitiveProperty]]
class "owl:SymetricProperty" [[http://www.w3.org/2002/07/owl#TransitiveProperty]]
class "owl:ReflexiveProperty" [[http://www.w3.org/2002/07/owl#ReflexiveProperty]]
abstract class "rdf:Property" [[http://www.w3.org/1999/02/22-rdf-syntax-ns#Property]] #LightGreen
class "rdfs:Datatype" [[http://www.w3.org/2000/01/rdf-schema#Datatype]] #LightGreen
class "owl:NamedIndividual" [[http://www.w3.org/2002/07/owl#NamedIndividual]] #LightGreen
abstract class "owl:Thing" [[http://www.w3.org/2002/07/owl#Thing]]{ 
  [[http://www.w3.org/2000/01/rdf-schema#label rdfs:label ]]: xsd:string
 [[http://www.w3.org/2000/01/rdf-schema#comment rdfs:comment ]]  : "xsd:string" 
}

"owl:Thing" <|--  "owl:Class"


"owl:Thing" <|--   "rdf:Property"
"owl:Thing" <|--   "rdfs:Datatype"
"owl:Thing" <|--   "owl:NamedIndividual"
"owl:NamedIndividual" <|-- "skos:Concept"
"rdf:Property" <|-- "owl:DatatypeProperty"
"rdf:Property" <|-- "owl:ObjectProperty"

"owl:ObjectProperty" <|-- "owl:TransitiveProperty"
"owl:ObjectProperty" <|-- "owl:SymetricProperty"
"owl:ObjectProperty" <|-- "owl:ReflexiveProperty"

"owl:ObjectProperty" --> "owl:ObjectProperty" : "owl:inverseOF"

"rdf:Property"--> "owl:Class" : "rdfs:domain"
"owl:ObjectProperty"--> "owl:Class" : "rdfs:range"
"owl:DatatypeProperty"--> "rdfs:Datatype" : "rdfs:range"
"owl:Class" --> "owl:Class" : "rdfs:subClassOf"
"owl:Class" --> "owl:Class" : "owl:disjointWith" 
"owl:Class" --> "owl:Class" : "owl:equivalentClass"
"rdf:Property" --> "rdf:Property" : "rdfs:subPropertyOf"
"owl:Thing" --> "owl:Class" : "rdf:type"
"owl:Class" -->  "skos:Concept" : "dct:subject"
"rdf:Property" -->  "skos:Concept" : "dct:subject"
"owl:NamedIndividual" --> "owl:NamedIndividual" : "owl:sameAs"
"owl:NamedIndividual" --> "owl:NamedIndividual" : "owl:differentFrom"

@enduml